//
// Generated file, do not edit! Created by nedtool 5.6 from ConfigurationMsg.msg.
//

#ifndef __CONFIGURATIONMSG_M_H
#define __CONFIGURATIONMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ConfigurationMsg.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet ConfigurationMsg
 * {
 *     //    \@customize(true);  // see the generated C++ header for more info
 *     //    int someField;
 *     //    abstract int anotherField;
 *     int startingNode;
 *     double startingTime;
 * }
 * </pre>
 */
class ConfigurationMsg : public ::omnetpp::cPacket
{
  protected:
    int startingNode;
    double startingTime;

  private:
    void copy(const ConfigurationMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConfigurationMsg&);

  public:
    ConfigurationMsg(const char *name=nullptr, short kind=0);
    ConfigurationMsg(const ConfigurationMsg& other);
    virtual ~ConfigurationMsg();
    ConfigurationMsg& operator=(const ConfigurationMsg& other);
    virtual ConfigurationMsg *dup() const override {return new ConfigurationMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getStartingNode() const;
    virtual void setStartingNode(int startingNode);
    virtual double getStartingTime() const;
    virtual void setStartingTime(double startingTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConfigurationMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConfigurationMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONFIGURATIONMSG_M_H

